AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  TheStackName:
    Type: String
    Description: The name of the stack

  ChessfinderApiDomainName:
    Type: String

  ChessfinderCertificateArn:
    Type: String

  ChessfinderLambdaRoleArn:
    Type: String

  DownloadGamesQueueUrl:
    Type: String

  SearchBoardQueueUrl:
    Type: String

  DownloadsTableName:
    Type: String
  
  UsersTableName:
    Type: String

  ArchivesTableName:
    Type: String
  
  SearchesTableName:
    Type: String

  ChessfinderValidationCoreFunctionName:
    Type: String

  ChessDotComUrl:
    Type: String
  
Resources:
  ChessfinderCustomDomainName:
    Properties:
      DomainName: !Ref ChessfinderApiDomainName
      DomainNameConfigurations:
        - CertificateArn: !Ref ChessfinderCertificateArn
          SecurityPolicy: TLS_1_2
          EndpointType: REGIONAL
    Type: AWS::ApiGatewayV2::DomainName
  
  ChessfinderHttpApi:
    Properties:
      Name: !Sub "${TheStackName}-ChessfinderHttpApi"
      StageName: $default
      CorsConfiguration:
        AllowOrigins:
          - "http://localhost:8080"
          - "https://demo.chessfinder.org"
          - "https://www.chessfinder.org"
          - "https://chessfinder.org"
        AllowHeaders:
          - "*"
        AllowMethods: [GET, POST, OPTIONS]
        MaxAge: 300
        AllowCredentials: false
    Type: AWS::Serverless::HttpApi
    DependsOn: ChessfinderCustomDomainName
  
  ChessfinderApiMapping:
    Properties:
      ApiId: !Ref ChessfinderHttpApi
      DomainName: !Ref ChessfinderApiDomainName
      Stage: $default
    Type: AWS::ApiGatewayV2::ApiMapping
    DependsOn: ChessfinderCustomDomainName
  
  CheckDownloadLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${TheStackName}/CheckDownload"
      RetentionInDays: 7

  CheckDownloadFunction:
    Properties:
      FunctionName: !Sub "${TheStackName}-CheckDownload"
      Timeout: 29
      MemorySize: 256
      Events:
        GetApiFasterGame:
          Properties:
            ApiId: !Ref ChessfinderHttpApi
            Method: GET
            Path: /api/faster/game
            TimeoutInMillis: 29000
            PayloadFormatVersion: '2.0'
          Type: HttpApi
      Architectures: ["arm64"]
      Runtime: "provided.al2"
      CodeUri: ../src_go/download/check_status/check_status.zip
      Handler: bootstrap
      Environment:
        Variables:
          DOWNLOADS_TABLE_NAME: !Ref DownloadsTableName
      Role: !Ref ChessfinderLambdaRoleArn
      LoggingConfig:
        LogFormat: JSON
        LogGroup: !Ref CheckDownloadLogs
    Type: AWS::Serverless::Function
  
  InitiateDownloadLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${TheStackName}/InitiateDownload"
      RetentionInDays: 7

  InitiateDownloadFunction:
    Properties:
      FunctionName: !Sub "${TheStackName}-InitiateDownload"
      Timeout: 29
      MemorySize: 256
      Events:
        PostApiFasterGame:
          Properties:
            ApiId: !Ref ChessfinderHttpApi
            Method: POST
            Path: /api/faster/game
            TimeoutInMillis: 29000
            PayloadFormatVersion: '2.0'
          Type: HttpApi
      Architectures: ["arm64"]
      Runtime: "provided.al2"
      CodeUri: ../src_go/download/initiate/initiate.zip
      Handler: bootstrap
      Environment:
        Variables:
          THE_STACK_NAME: !Ref TheStackName
          DOWNLOAD_GAMES_QUEUE_URL: !Ref DownloadGamesQueueUrl
          CHESS_DOT_COM_URL: !Ref ChessDotComUrl
          DOWNLOADS_TABLE_NAME: !Ref DownloadsTableName
          USERS_TABLE_NAME: !Ref UsersTableName
          ARCHIVES_TABLE_NAME: !Ref ArchivesTableName
      Role: !Ref ChessfinderLambdaRoleArn
      LoggingConfig:
        LogFormat: JSON
        LogGroup: !Ref InitiateDownloadLogs
    Type: AWS::Serverless::Function

  CheckSearchLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${TheStackName}/CheckSearch"
      RetentionInDays: 7
  
  CheckSearchFunction:
    Properties:
      FunctionName: !Sub "${TheStackName}-CheckSearch"
      Timeout: 29
      MemorySize: 256
      Events:
        GetApiFasterBoard:
          Properties:
            ApiId: !Ref ChessfinderHttpApi
            Method: GET
            Path: /api/faster/board
            TimeoutInMillis: 29000
            PayloadFormatVersion: '2.0'
          Type: HttpApi
      Architectures: ["arm64"]
      Runtime: "provided.al2"
      CodeUri: ../src_go/search/check_status/check_status.zip
      Handler: bootstrap
      Environment:
        Variables:
          SEARCHES_TABLE_NAME: !Ref SearchesTableName
      Role: !Ref ChessfinderLambdaRoleArn
      LoggingConfig:
        LogFormat: JSON
        LogGroup: !Ref CheckSearchLogs
    Type: AWS::Serverless::Function

  InitiateSearchLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${TheStackName}/InitiateSearch"
      RetentionInDays: 7
  
  InitiateSearchFunction:
    Properties:
      FunctionName: !Sub "${TheStackName}-InitiateSearch"
      Timeout: 29
      MemorySize: 1024
      Events:
        PostApiFasterGame:
          Properties:
            ApiId: !Ref ChessfinderHttpApi
            Method: POST
            Path: /api/faster/board
            TimeoutInMillis: 29000
            PayloadFormatVersion: '2.0'
          Type: HttpApi
      Architectures: ["x86_64"]
      Runtime: "provided.al2"
      CodeUri: ../src_go/search/initiate/initiate.zip
      Handler: bootstrap
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref UsersTableName
          CHESSFINDER_VALIDATION_CORE_FUNCTION_NAME: !Ref ChessfinderValidationCoreFunctionName
          ARCHIVES_TABLE_NAME: !Ref ArchivesTableName
          SEARCHES_TABLE_NAME: !Ref SearchesTableName
          SEARCH_BOARD_QUEUE_URL: !Ref SearchBoardQueueUrl
      Role: !Ref ChessfinderLambdaRoleArn
      LoggingConfig:
        LogFormat: JSON
        LogGroup: !Ref InitiateSearchLogs
    Type: AWS::Serverless::Function

Outputs:
  ChessfinderApiRegionalDomainName: 
    Description: "Chessfinder API Regional Domain Name"
    Value: !GetAtt ChessfinderCustomDomainName.RegionalDomainName
  ChessfinderApiRegionalHostedZoneId:
    Description: "Chessfinder API Regional Hosted Zone Id"
    Value: !GetAtt ChessfinderCustomDomainName.RegionalHostedZoneId
