AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  ChessfinderLambdaRoleArn:
    Type: String
    Description: Lambda role for basic execution and permissions

  ChessDotComUrl:
    Type: String
    Description: URL for chess.com API
  
  DownloadsTableName:
    Type: String
    Description: DynamoDB table for downloads
  
  ArchivesTableName:
    Type: String
    Description: DynamoDB table for archives
  
  GamesTableName:
    Type: String
    Description: DynamoDB table for games 
  
  GamesByEndTimestampIndexName:
    Type: String
    Description: DynamoDB index for games by end timestamp

  SearchesTableName:
    Type: String
    Description: DynamoDB table for searches
    
  DownloadGamesQueueArn:
    Type: String
  
  SearchBoardQueueArn:
    Type: String
  
Resources:
  DownloadGamesFunction:
    Properties:
      FunctionName: !Sub ${AWS::StackName}-DownloadGames
      MemorySize: 1024
      Events:
        DownloadGamesCommand:
          Properties:
            Queue: !Ref 'DownloadGamesQueueArn'
            BatchSize: 10
          Type: SQS
      Timeout: 900
      Architectures: ["arm64"]
      Runtime: "provided.al2"
      CodeUri: ../src_go/download/process/process.zip
      Handler: bootstrap
      Environment:
        Variables:
          CHESS_DOT_COM_URL: !Ref ChessDotComUrl
          DOWNLOADS_TABLE_NAME: !Ref DownloadsTableName
          ARCHIVES_TABLE_NAME: !Ref ArchivesTableName
          GAMES_TABLE_NAME: !Ref GamesTableName
          GAMES_BY_END_TIMESTAMP_INDEX_NAME: !Ref GamesByEndTimestampIndexName
      Role: !Ref 'ChessfinderLambdaRoleArn'
    Type: AWS::Serverless::Function

  SearchBoardFunction:
    Properties:
      FunctionName: !Sub ${AWS::StackName}-SearchBoard
      MemorySize: 2048
      Events:
        SearchBoardCommand:
          Properties:
            Queue: !Ref 'SearchBoardQueueArn'
            BatchSize: 1
          Type: SQS
      Timeout: 900
      Architectures: ["x86_64"]
      Runtime: "provided.al2"
      CodeUri: ../src_go/search/process/process.zip
      Handler: bootstrap
      Environment:
        Variables:
          SEARCHES_TABLE_NAME: !Ref SearchesTableName
          GAMES_TABLE_NAME: !Ref GamesTableName
      Role: !Ref 'ChessfinderLambdaRoleArn'
    Type: AWS::Serverless::Function
