AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  TheStackName:
    Type: String
    Description: The name of the stack
  ChessfinderLambdaRoleArn:
    Type: String

Resources:
  ChessfinderCoreLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${TheStackName}/ChessfinderCore"
      RetentionInDays: 30
    
  ChessfinderCoreFunction:
    Properties:
      FunctionName: !Sub "${TheStackName}-ChessfinderCore"
      Timeout: 29
      MemorySize: 1024
      Runtime: java17
      CodeUri: ../target/scala-3.3.0/chessfinder-lambda.jar
      Handler: chessfinder.api.Lambda::handleRequest
      Role: !Ref 'ChessfinderLambdaRoleArn'
      LoggingConfig:
        LogFormat: JSON
        LogGroup: !Ref ChessfinderCoreLogs
    Type: AWS::Serverless::Function


Outputs:
  ChessfinderCoreFunctionName:
    Value: !Ref ChessfinderCoreFunction
    