AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  TheStackName:
    Type: String
    Description: The name of the stack
  ChessfinderLambdaRoleArn:
    Type: String

Resources:
  ChessfinderSearchCoreLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${TheStackName}/ChessfinderSearchCore"
      RetentionInDays: 7
    
  ChessfinderSearchCoreFunction:
    Properties:
      FunctionName: !Sub "${TheStackName}-ChessfinderSearchCore"
      Timeout: 29
      MemorySize: 1024
      Runtime: java17
      CodeUri: ../target/scala-3.3.0/chessfinder-lambda.jar
      Handler: chessfinder.api.SearchLambda::handleRequest
      Role: !Ref 'ChessfinderLambdaRoleArn'
      LoggingConfig:
        LogFormat: JSON
        LogGroup: !Ref ChessfinderSearchCoreLogs
    Type: AWS::Serverless::Function

  ChessfinderValidationCoreLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${TheStackName}/ChessfinderValidationCore"
      RetentionInDays: 7
    
  ChessfinderValidationCoreFunction:
    Properties:
      FunctionName: !Sub "${TheStackName}-ChessfinderValidationCore"
      Timeout: 29
      MemorySize: 1024
      Runtime: java17
      CodeUri: ../target/scala-3.3.0/chessfinder-lambda.jar
      Handler: chessfinder.api.ValidationLambda::handleRequest
      Role: !Ref 'ChessfinderLambdaRoleArn'
      LoggingConfig:
        LogFormat: JSON
        LogGroup: !Ref ChessfinderValidationCoreLogs
    Type: AWS::Serverless::Function  


Outputs:
  ChessfinderSearchCoreFunctionName:
    Value: !Ref ChessfinderSearchCoreFunction

  ChessfinderValidationCoreFunctionName:
    Value: !Ref ChessfinderValidationCoreFunction   
