AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  chessfinder caching with dynamodb

Parameters:
  TheStackName:
    Type: String
    Description: The name of the stack

Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${TheStackName}-users"
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
        - AttributeName: platform
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
        - AttributeName: platform
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  DownloadsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${TheStackName}-downloads"
      AttributeDefinitions:
        - AttributeName: download_id
          AttributeType: S
        - AttributeName: consistent_download_id
          AttributeType: S
        - AttributeName: expires_at
          AttributeType: N
      KeySchema:
        - AttributeName: download_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: !Sub "${TheStackName}-downloadsByConsistentDownloadId"
          KeySchema:
            - AttributeName: consistent_download_id
              KeyType: HASH
            - AttributeName: expires_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true

  GamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${TheStackName}-games"
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: game_id
          AttributeType: S
        - AttributeName: archive_id
          AttributeType: S
        - AttributeName: end_timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: game_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: !Sub "${TheStackName}-gamesByEndTimestamp"
          KeySchema:
            - AttributeName: archive_id
              KeyType: HASH
            - AttributeName: end_timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  ArchivesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${TheStackName}-archives"
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: archive_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: archive_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  SearchesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${TheStackName}-searches"
      AttributeDefinitions:
        - AttributeName: search_id
          AttributeType: S
        - AttributeName: consistent_search_id
          AttributeType: S
        - AttributeName: expires_at
          AttributeType: N
      KeySchema:
        - AttributeName: search_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: !Sub "${TheStackName}-searchesByConsistentSearchId"
          KeySchema:
            - AttributeName: consistent_search_id
              KeyType: HASH
            - AttributeName: expires_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true

Outputs:
  UsersTableName:
    Description: "Users Table Name"
    Value: !Ref UsersTable
  DownloadsTableName:
    Description: "Downloads Table Name"
    Value: !Ref DownloadsTable
  DownloadsByConsistentDownloadIdIndexName:
    Description: "Downloads By Consistent Download Id Index Name"
     # this is a shame that we have to hardcode this
    # Value: "!GetAtt ???.0.IndexName"
    Value: !Sub "${TheStackName}-downloadsByConsistentDownloadId"
  GamesTableName:
    Description: "Games Table Name"
    Value: !Ref GamesTable
  GamesByEndTimestampIndexName:
    Description: "Games By End Timestamp Index Name"
     # this is a shame that we have to hardcode this
    # Value: "!GetAtt ???.0.IndexName"
    Value: !Sub "${TheStackName}-gamesByEndTimestamp"
  ArchivesTableName:
    Description: "Archives Table Name"
    Value: !Ref ArchivesTable
  SearchesTableName:
    Description: "Searches Table Name"
    Value: !Ref SearchesTable
  SearchesByConsistentSearchIdIndexName:
    Description: "Searches By Consistent Search Id Index Name"
     # this is a shame that we have to hardcode this
    # Value: "!GetAtt ???.0.IndexName"
    Value: !Sub "${TheStackName}-searchesByConsistentSearchId"
