AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  TheStackName:
    Type: String
    Description: The name of the stack

Resources:
  DownloadGames: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Sub "${TheStackName}-DownloadGames.fifo"
      FifoQueue: true
      VisibilityTimeout: 900
      MessageRetentionPeriod: 1899
      ContentBasedDeduplication: false

  SearchBoard:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Sub "${TheStackName}-SearchBoard.fifo"
      FifoQueue: true
      VisibilityTimeout: 900
      MessageRetentionPeriod: 1899
      ContentBasedDeduplication: false

Outputs:
  DownloadGamesQueueUrl: 
    Description: "URL of DownloadGamesQueue"
    Value: !Ref DownloadGames
  DownloadGamesQueueArn: 
    Description: "ARN of DownloadGamesQueue"
    Value: !GetAtt DownloadGames.Arn
  
  SearchBoardQueueUrl: 
    Description: "URL of SearchBoardQueue"
    Value: !Ref SearchBoard
  SearchBoardQueueArn: 
    Description: "ARN of SearchBoardQueue"
    Value: !GetAtt SearchBoard.Arn
