AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  DownloadGames: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Sub "${AWS::StackName}-DownloadGames.fifo"
      FifoQueue: true
      VisibilityTimeout: 900

  SearchBoard: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Sub "${AWS::StackName}-SearchBoard.fifo"
      FifoQueue: true
      VisibilityTimeout: 900

Outputs:
  DownloadGamesQueueUrl: 
    Description: "URL of DownloadGamesQueue"
    Value: !Ref DownloadGames
  DownloadGamesQueueArn: 
    Description: "ARN of DownloadGamesQueue"
    Value: !GetAtt DownloadGames.Arn
  
  SearchBoardQueueUrl: 
    Description: "URL of SearchBoardQueue"
    Value: !Ref SearchBoard
  SearchBoardQueueArn: 
    Description: "ARN of SearchBoardQueue"
    Value: !GetAtt SearchBoard.Arn
