version: '3.9'

services:

  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock
    restart: "no"
    hostname: wiremock
    ports:
      - "${WIREMOCK_EXPOSED_PORT}:8443"
    command:
      [
        "--port",
        "8443",
        "--max-request-journal",
        "1000",
        "--local-response-templating",
        "--root-dir",
        "/home/wiremock/storage"
      ]
  
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      # - "127.0.0.1:4510-4559:4510-4559"  # ext services port range
      # - "127.0.0.1:53:53"                # DNS config
      # - "127.0.0.1:53:53/udp"            # DNS config
      # - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway
    environment:
      - DEBUG=1
      - EAGER_SERVICE_LOADING=1
      - SERVICES=sqs,secretsmanager,dynamodb,lambda,iam
      # - LS_LOG=trace-internal
      # - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      # - "${STORAGE}/code/localstack/localstack:/opt/code/localstack/localstack"
      # - "C:\\Users\\tohanyan\\IdeaProjects\\localstack\\localstack:/opt/code/localstack/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
